name: 'foo'
version: '1.0.0'
config-version: 2

profile: 'foo'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:

seeds:
  foo:
    cities:
    countries:
      location_root: "{{ env_var('LOCATION') }}"